### ISSUE TITLE
Commit 697a150 has Windows errors

### ISSUE THREAD

**Issue by Omniferum** [juancarlospaco/css-html-js-minify#27]
```python
Traceback (most recent call last):
  File "css-html-js-minify.py", line 38, in <module>
    import resource  # windows dont have resource
ImportError: No module named 'resource'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "css-html-js-minify.py", line 41, in <module>
    from StringIO import StringIO  # lint:ok
ImportError: No module named 'StringIO'
Traceback (most recent call last):
  File "css-html-js-minify.py", line 38, in <module>
    import resource  # windows dont have resource
ImportError: No module named 'resource'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "css-html-js-minify.py", line 41, in <module>
    from StringIO import StringIO  # lint:ok
ImportError: No module named 'StringIO'
```

**Comment by Omniferum** [comment]
Number of Files Processed: 1.
Traceback (most recent call last):
  File "css-html-js-minify.py", line 1386, in <module>
    main()
  File "css-html-js-minify.py", line 1382, in main
    make_post_execution_message()
  File "css-html-js-minify.py", line 1271, in make_post_execution_message
    msg = "Total Maximum RAM Memory used: ~{0} of {1}MegaBytes".format(use, al)
UnboundLocalError: local variable 'use' referenced before assignment

**Comment by Omniferum** [comment]
Huzzah. All good.

Still a mighty fine .py script. Useful as hell.

**Comment by juancarlospaco** [comment]
# d-( ʘ‿ʘ )_m
