### ISSUE TITLE
Does not run out of the box on Windows - ImportError: No module named 'resource'

### ISSUE THREAD

**Issue by nueverest** [juancarlospaco/css-html-js-minify#29]
Windows command line:
```python
C:\changeyourenergy\style>python C:\Python34\Scripts\css-html-js-minify.py screen.css
Traceback (most recent call last):
  File "C:\Python34\Scripts\css-html-js-minify.py", line 38, in <module>
    import resource  # windows dont have resource
ImportError: No module named 'resource'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\css-html-js-minify.py", line 41, in <module>
    from StringIO import StringIO  # lint:ok
ImportError: No module named 'StringIO'
```

In `css-html-js-minify` is see:
```python
try:
    import resource  # windows dont have resource
except ImportError:
    resource = None
```

How do I get this to work for Windows?

**Comment by cassiobotaro** [comment]
Just update your version of css-html-js-minify,  caa1ace3a already fixed it!

**Comment by juancarlospaco** [comment]
Update your version of css-html-js-minify.

**Comment by slavkoja** [comment]
I see regression here on Windows (Python 3.4). I installed the 1.2.2 version from pypi and i get the same error. I checked mentioned commit, but in my ``css-html-js-minify.py`` i see:
```python
try:
    from urllib import request
    from subprocess import getoutput
    from shutil import disk_usage
    from io import StringIO  # pure-Python StringIO supports unicode.
    import resource  # windows dont have resource
except ImportError:
    request = getoutput = disk_usage = resource = None
    from StringIO import StringIO  # lint:ok

__version__ = '1.2.2'
```
regards

**Comment by juancarlospaco** [comment]
All that code will dissapear, for good, it will be replaced with the one on a new helper utility lib Im working on here, is WIP: https://github.com/juancarlospaco/anglerfish#anglerfish
