### ISSUE TITLE
Fails to install due to lack of required package

### ISSUE THREAD

**Issue by mktoni** [juancarlospaco/css-html-js-minify#36]
Fails to install due to lack of anglerfish module, maybe it is not listed in ```install_requires```.
If anglerfish was manually installed, css-html-js-minify installs fine.

```bash
$ python3 --version
Python 3.4.0

$ pip3 --version
pip 8.1.2 from /usr/local/lib/python3.4/dist-packages (python 3.4)

$ sudo -H pip3 install css-html-js-minify
Collecting css-html-js-minify
  Using cached css-html-js-minify-2.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-odl9m2zv/css-html-js-minify/setup.py", line 34, in <module>
        import css_html_js_minify
      File "/tmp/pip-build-odl9m2zv/css-html-js-minify/css_html_js_minify/__init__.py", line 11, in <module>
        from .minify import (process_single_html_file, process_single_js_file,
      File "/tmp/pip-build-odl9m2zv/css-html-js-minify/css_html_js_minify/minify.py", line 28, in <module>
        from anglerfish import (check_encoding, check_folder, make_logger,
    ImportError: No module named 'anglerfish'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-odl9m2zv/css-html-js-minify/
```

**Comment by mktoni** [comment]
How much time until it be replicated to PyPi?

**Comment by juancarlospaco** [comment]
PIP can install from Git.
But soon should be ready...

**Comment by juancarlospaco** [comment]
Ready.
https://pypi.python.org/pypi/css-html-js-minify

**Comment by mktoni** [comment]
@juancarlospaco still facing this issue when installig css-html-js-minify either from PyPi or from GitHub repository.

I think the setup process is relying on anglerfish module when it isn't yet available. The anglerfish module seems to be a requirement not only to the install but to the setup process too.

There is a ```setup_requires``` keyword to specify what other distributions need to be present in order for the setup script to run, I included it in the setup( ) but it doesn't work.

Follows the traceback:

```bash
$ sudo pip3 install git+https://github.com/juancarlospaco/css-html-js-minify.git#egg=css-html-js-minify
Downloading/unpacking css-html-js-minify from git+https://github.com/juancarlospaco/css-html-js-minify.git
  Cloning https://github.com/juancarlospaco/css-html-js-minify.git to /tmp/pip_build_root/css-html-js-minify
  Running setup.py (path:/tmp/pip_build_root/css-html-js-minify/setup.py) egg_info for package css-html-js-minify
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/css-html-js-minify/setup.py", line 34, in <module>
        import css_html_js_minify
      File "/tmp/pip_build_root/css-html-js-minify/css_html_js_minify/__init__.py", line 11, in <module>
        from .minify import (process_single_html_file, process_single_js_file,
      File "/tmp/pip_build_root/css-html-js-minify/css_html_js_minify/minify.py", line 28, in <module>
        from anglerfish import (check_encoding, check_folder, make_logger,
    ImportError: No module named 'anglerfish'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/css-html-js-minify/setup.py", line 34, in <module>

    import css_html_js_minify

  File "/tmp/pip_build_root/css-html-js-minify/css_html_js_minify/__init__.py", line 11, in <module>

    from .minify import (process_single_html_file, process_single_js_file,

  File "/tmp/pip_build_root/css-html-js-minify/css_html_js_minify/minify.py", line 28, in <module>

    from anglerfish import (check_encoding, check_folder, make_logger,

ImportError: No module named 'anglerfish'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/css-html-js-minify
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

**Comment by hwkns** [comment]
@juancarlospaco could you release this fix to PyPI?

**Comment by juancarlospaco** [comment]
It should be already: https://github.com/juancarlospaco/css-html-js-minify/blob/master/setup.py#L117

**Comment by hwkns** [comment]
No, @juancarlospaco that change did not actually fix the issue; `setup.py` was still importing the project.  @mktoni fixed it in https://github.com/juancarlospaco/css-html-js-minify/pull/37 but that update has not been released to PyPI.

**Comment by juancarlospaco** [comment]
https://pypi.python.org/pypi/css-html-js-minify/2.2.2

Thats a new version. I see the same `setup.py` there than in the Git repo. 
Try cleaning your pip local cache and re-install. If it did not work post the whole install/run/execution output on terminal.

**Comment by hwkns** [comment]
2.2.2 works! <3
