### ISSUE TITLE
NameError: name 'log' is not defined

### ISSUE THREAD

**Issue by jdsutton** [juancarlospaco/css-html-js-minify#51]
```
Traceback (most recent call last):
  File "FrontendTools/minifier.py", line 33, in <module>
    main()
  File "FrontendTools/minifier.py", line 26, in main
    process_single_js_file(file, overwrite=True)
  File "/usr/local/lib/python3.5/dist-packages/css_html_js_minify/minify.py", line 174, in process_single_js_file
    log.info("Processing JS file: {0}.".format(js_file_path))
NameError: name 'log' is not defined
```

**Comment by juancarlospaco** [comment]
Thanks :grey_exclamation:  :smile_cat:
