### ISSUE TITLE
When i try to run i got this error.

### ISSUE THREAD

**Issue by cassiobotaro** [juancarlospaco/css-html-js-minify#6]
```shell
CSS-HTML-JS-Minify.

StandAlone Async single-file cross-platform no-dependencies
Unicode-ready Python3-ready Minifier for the Web.
1.0.11 
Target is a Folder with CSS, HTML, JS. 
Processing a whole Folder may take some time... 
Traceback (most recent call last):
  File "css-html-js-minify.py", line 1206, in <module>
    main()
  File "css-html-js-minify.py", line 1185, in main
    tuple() if args.overwrite else (".min.css", ".min.js", ".htm"))
  File "css-html-js-minify.py", line 880, in walkdir_to_filelist
    """.format(where, target.upper(), omit.upper()))
AttributeError: 'tuple' object has no attribute 'upper'
```

**Comment by cassiobotaro** [comment]
The problem is with this commit https://github.com/juancarlospaco/css-html-js-minify/commit/a98ee269325cad2ca3f06da9a3e1fae3d65f050b
Before, it works!

**Comment by juancarlospaco** [comment]
Fixed now; Thanks for the Report ! :octocat:
