### ISSUE TITLE
Python error in example

### ISSUE THREAD

**Issue by warrenspe** [juancarlospaco/css-html-js-minify#67]
```
$ python3
Python 3.6.1 (default, Mar 21 2017, 21:49:16)
[GCC 5.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from css_html_js_minify import process_single_html_file, process_single_js_file, process_single_css_file, html_minify, js_minify, css_minify
>>> process_single_js_file("test.js")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/css_html_js_minify/minify.py", line 174, in process_single_js_file
    log.info("Processing JS file: {0}.".format(js_file_path))
NameError: name 'log' is not defined
```

**Comment by juancarlospaco** [comment]
WIP Fix for this is on active Development, we hope to have it ASAP, but its happening somewhere else:
https://github.com/juancarlospaco/anglerfish#angler

**Comment by juancarlospaco** [comment]
Fixed on master.
